org: joshsummer
app: aws-node-express-dynamodb-api
service: aws-node-express-dynamodb-api
frameworkVersion: '3'

custom:
  #tableName: 'users-table-${sls:stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      #inMemory: true
      #heapInitial: 200m
      #heapMax: 1g
      migrate: true
      #seed: false
      #convertEmptyValues: true
      #docker: true
  serverless-offline:
    httpPort: 3000
    lamdaPort: 3001      


provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: employee #${self:custom.tableName}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          method: GET
          path: /empleado
      - httpApi:
          method: GET
          path: /empleado/{employeeid}
      - httpApi:
          method: POST
          path: /empleado

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employee
        AttributeDefinitions:
          - AttributeName: employeeid
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: age
            AttributeType: S
          - AttributeName: cargo
            AttributeType: S      
        KeySchema:
          - AttributeName: employeeid
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5            
        GlobalSecondaryIndexes:
          - IndexName: age_cargo
            KeySchema: 
              - AttributeName: age
                KeyType: HASH
              - AttributeName: cargo
                KeyType: RANGE  
            Projection:
              NonKeyAttributes: []
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5            
        
plugins:
  - serverless-dynamodb-local
  - serverless-offline